# Generated by Django 4.2.5 on 2023-09-22 19:25

import functools

import django.core.validators
from django.db import migrations, models

import vehicles.utils


class Migration(migrations.Migration):
    initial = True

    dependencies: list[str] = []

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'code',
                    models.CharField(
                        default=functools.partial(
                            vehicles.utils.generate_random_code, *(), **{}
                        ),
                        help_text='Unique code of vehicle',
                        max_length=5,
                        unique=True,
                        verbose_name='code',
                    ),
                ),
                (
                    'capacity',
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text='Cargo carrying capacity of the vehicle',
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                        verbose_name='capacity',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ('-pk',),
            },
        ),
    ]
