# Generated by Django 4.2.5 on 2023-09-22 19:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('locations', '0002_auto_20230921_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'weight',
                    models.PositiveSmallIntegerField(
                        help_text='Cargo weight',
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                        verbose_name='weight',
                    ),
                ),
                (
                    'description',
                    models.CharField(
                        help_text='Cargo description',
                        max_length=1000,
                        verbose_name='description',
                    ),
                ),
                (
                    'delivery_location',
                    models.ForeignKey(
                        help_text='Cargo delivery location',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='delivery_locations',
                        to='locations.location',
                        verbose_name='delivery_location',
                    ),
                ),
                (
                    'pickup_location',
                    models.ForeignKey(
                        help_text='Cargo pick-up location',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='pickup_locations',
                        to='locations.location',
                        verbose_name='pickup_location',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargoes',
                'ordering': ('-pk',),
            },
        ),
        migrations.AddConstraint(
            model_name='cargo',
            constraint=models.CheckConstraint(
                check=models.Q(
                    ('delivery_location', models.F('pickup_location')), _negated=True
                ),
                name='same_pickup_delivery_location_constraint',
            ),
        ),
    ]
