# Generated by Django 4.2.5 on 2023-09-23 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vehicles', '0001_initial'),
        ('cargo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='vehicle',
            field=models.ForeignKey(
                blank=True,
                help_text='Transporting vehicle',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='cargoes',
                to='vehicles.vehicle',
                verbose_name='vehicle',
            ),
        ),
    ]
