# Generated by Django 4.2.5 on 2023-09-21 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list[str] = []

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Name of city',
                        max_length=100,
                        verbose_name='name',
                    ),
                ),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'state_id',
                    models.CharField(
                        help_text='2-letter ID of state',
                        max_length=2,
                        unique=True,
                        verbose_name='state_id',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Name of state',
                        max_length=100,
                        unique=True,
                        verbose_name='name',
                    ),
                ),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'zip_code',
                    models.CharField(
                        help_text='Zip code of location',
                        max_length=6,
                        unique=True,
                        verbose_name='zip_code',
                    ),
                ),
                (
                    'latitude',
                    models.FloatField(help_text='Latitude', verbose_name='latitude'),
                ),
                (
                    'longitude',
                    models.FloatField(help_text='Logitude', verbose_name='longitude'),
                ),
                (
                    'city',
                    models.ForeignKey(
                        help_text='City where location placed',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='locations',
                        to='locations.city',
                        verbose_name='city',
                    ),
                ),
                (
                    'state',
                    models.ForeignKey(
                        help_text='State where location placed',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='locations',
                        to='locations.state',
                        verbose_name='state',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ('-pk',),
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(
                help_text='State in which city placed',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='cities',
                to='locations.state',
                verbose_name='state',
            ),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(
                check=models.Q(('latitude__gte', -90), ('latitude__lte', 90)),
                name='latitude_value_constraint',
            ),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(
                check=models.Q(('longitude__gte', -180), ('longitude__lte', 180)),
                name='longitude_value_constraint',
            ),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(
                fields=('name', 'state'),
                name='unique_city_state',
            ),
        ),
    ]
