# Generated by Django 4.2.5 on 2023-09-22 20:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('locations', '0002_auto_20230921_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='state',
        ),
    ]
