# Generated by Django 4.2.5 on 2023-09-23 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('locations', '0003_remove_location_state'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'location',
                    models.ForeignKey(
                        help_text='Location',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tracks',
                        to='locations.location',
                        verbose_name='location',
                    ),
                ),
                (
                    'vehicle',
                    models.OneToOneField(
                        help_text='Vehicle',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='track',
                        to='vehicles.vehicle',
                        verbose_name='vehicle',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
                'ordering': ('-pk',),
            },
        ),
    ]
