# Generated by Django 4.2.5 on 2023-09-23 18:11

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={
                'ordering': ('-created_at',),
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
            },
        ),
        migrations.AddField(
            model_name='track',
            name='created_at',
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 23, 18, 11, 41, 205855, tzinfo=datetime.timezone.utc
                ),
                help_text='Track created at',
                verbose_name='created_at',
            ),
        ),
    ]
