# Generated by Django 4.2.5 on 2023-09-23 18:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={
                'ordering': ('-created_at',),
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
            },
        ),
        migrations.AddField(
            model_name='track',
            name='created_at',
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text='Track created at',
                verbose_name='created_at',
            ),
        ),
    ]
